package com.ma_recurit.entity.member;

public enum Job {
    BEGINNER,

    WARRIOR,
    FIGHTER, CRUSADER, HERO,
    PAGE, KNIGHT, PALADIN,
    SPEARMAN, BERSERKER, DARK_KNIGHT,

    MAGICIAN,
    WIZARD_FIRE_POISON, MAGE_FIRE_POISON, ARCHMAGE_FIRE_POISON,
    WIZARD_ICE_LIGHTNING, MAGE_ICE_LIGHTNING, ARCHMAGE_ICE_LIGHTNING,
    CLERIC, PRIEST, BISHOP,

    ARCHER,
    HUNTER, RANGER, BOWMASTER,
    CROSSBOWMAN, SNIPER, MARKSMAN,

    THIEF,
    ASSASSIN, HERMIT, NIGHT_LORD,
    CHIEF, CHIEF_MASTER, SHADOWER,

    PIRATE,
    INFIGHTER, BUCCANEER, VIPER,
    GUNSLINGER, OUTLAW, CAPTAIN
}
